
import OrderFoodBanner from "@/components/OrderFoodBanner";
import { FoodData } from "@/types/FoodOrder";

export default function FoodOrder() {

const foodData: FoodData[] = [
  {
    name: "Margherita Pizza",
    cuisinetype: "Italian",
    price: "$12",
    deliverytime: "30 mins",
    deliverprice: "$2",
    rating: "4.6",
    totalorders: 1200,
    photourl: "/pizza.png",
    bgcolor: "#F3F6FD", 
  },
  {
    name: "Cheeseburger",
    cuisinetype: "American",
    price: "$10",
    deliverytime: "25 mins",
    deliverprice: "$1.5",
    rating: "4.4",
    totalorders: 950,
     photourl:  "/cheeseburger.png",
    bgcolor: "#FDF3F4", 
  },
  {
    name: "Chicken Biryani",
    cuisinetype: "Pakistani",
    price: "$8",
    deliverytime: "35 mins",
    deliverprice: "$1",
    rating: "4.8",
    totalorders: 2000,
     photourl: "/chickenbiryani.png",
    bgcolor: "#FDF9F3",
  },
  {
    name: "Sushi Platter",
    cuisinetype: "Japanese",
    price: "$18",
    deliverytime: "40 mins",
    deliverprice: "$3",
    rating: "4.7",
    totalorders: 750,
    photourl: "/sushiplater.png",
    bgcolor: "#F3FDF7", 
  },
  {
    name: "Pad Thai",
    cuisinetype: "Thai",
    price: "$14",
    deliverytime: "30 mins",
    deliverprice: "$2",
    rating: "4.5",
    totalorders: 680,
   photourl: "/padthai.png",
    bgcolor: "#F0E7E9", 
  },
  {
    name: "Tacos al Pastor",
    cuisinetype: "Mexican",
    price: "$9",
    deliverytime: "20 mins",
    deliverprice: "$1",
    rating: "4.3",
    totalorders: 830,
     photourl: "/tacosalposter.png",
    bgcolor: "#FDF3FB",
  },
  {
    name: "Shawarma Wrap",
    cuisinetype: "Middle Eastern",
    price: "$7",
    deliverytime: "25 mins",
    deliverprice: "$1",
    rating: "4.6",
    totalorders: 1100,
     photourl: "/shwarmawrap.png",
    bgcolor: "#F3FDFD", 
  },
  {
    name: "Pasta Alfredo",
    cuisinetype: "Italian",
    price: "$13",
    deliverytime: "30 mins",
    deliverprice: "$2",
    rating: "4.5",
    totalorders: 890,
    photourl: "/alferedopasta.png",
    bgcolor: "#FFF9F3", 
  },
  {
    name: "Falafel Bowl",
    cuisinetype: "Mediterranean",
    price: "$11",
    deliverytime: "28 mins",
    deliverprice: "$1.5",
    rating: "4.2",
    totalorders: 640,
    photourl: "/falafelbowl.png",
    bgcolor: "#F8F3FD", 
  },
  {
    name: "Butter Chicken",
    cuisinetype: "Indian",
    price: "$15",
    deliverytime: "35 mins",
    deliverprice: "$2",
    rating: "4.8",
    totalorders: 1750,
     photourl: "/butterchicken.png",
    bgcolor: "#FDF3F8",
  },
  {
    name: "Pho Noodle Soup",
    cuisinetype: "Vietnamese",
    price: "$12",
    deliverytime: "32 mins",
    deliverprice: "$2",
    rating: "4.6",
    totalorders: 720,
     photourl: "/phonoodlesoap.png",
    bgcolor: "#F3F6FD",
  },
  {
    name: "Kebab Skewers",
    cuisinetype: "Turkish",
    price: "$14",
    deliverytime: "30 mins",
    deliverprice: "$2",
    rating: "4.7",
    totalorders: 960,
    photourl: "/kebabskewers.png",
    bgcolor: "#FDF3F4", 
  },
  {
    name: "Fried Chicken",
    cuisinetype: "American",
    price: "$11",
    deliverytime: "22 mins",
    deliverprice: "$1.5",
    rating: "4.4",
    totalorders: 1320,
     photourl: "/friedchicken.png",
    bgcolor: "#FDF9F3", 
  },
  {
    name: "Dim Sum Platter",
    cuisinetype: "Chinese",
    price: "$16",
    deliverytime: "38 mins",
    deliverprice: "$2.5",
    rating: "4.5",
    totalorders: 810,
     photourl: "/dimsumplater.png",
    bgcolor: "#F3FDF7", 
  },            
  {
    name: "Greek Salad",
    cuisinetype: "Greek",
    price: "$9",
    deliverytime: "18 mins",
    deliverprice: "$1",
    rating: "4.3",
    totalorders: 540,
     photourl: "/greeksalad.png",
    bgcolor: "#FDF3FB",
  },
];

  
 return (
    <div>
      <OrderFoodBanner foodData={foodData}/>
    </div>
  );
}
